// Hierarchical Energy Data Structure following Minimum Data Guidelines (MDG)
// Structure: Administration → Category → Theme → Sector → General Description → Baseline/Target → Unit → Status → Location → Years

export interface EnergyDataPoint {
  Administration: string // County name
  Category: string // Main category (Energy Resource Potential, Infrastructure & Access, Energy Demand & Consumption)
  Theme: string // Specific theme within category
  Sector: string // Energy type (Solar, Wind, Biomass, etc.)
  'General Description': string // Detailed description
  'Potential Energy Capacity'?: number // For resource potential
  'Unit of Measure': string
  'Status of Exploitation': string
  Location: string
  '2019'?: number
  '2020'?: number
  '2021'?: number
  '2022'?: number
  '2023'?: number
  '2024'?: number
  '2025'?: number
  '2026'?: number
  '2027'?: number
  '2028'?: number
  '2029'?: number
  '2030'?: number
  Notes: string
  Source: string
}

export const energyData: EnergyDataPoint[] = [
  // ============ NATIONAL DATA ============
  // ENERGY RESOURCE POTENTIAL
  {
    Administration: 'NATIONAL',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Average solar radiation across Kenya',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Kenya',
    '2024': 5.2,
    Notes: 'National average solar potential',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Wind',
    'General Description': 'Average wind potential across Kenya',
    'Unit of Measure': 'm/s',
    'Status of Exploitation': 'Assessed',
    Location: 'Kenya',
    '2024': 5.8,
    Notes: 'National average wind speed',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Biomass',
    'General Description': 'Wood fuel availability',
    'Unit of Measure': 'tonnes/yr',
    'Status of Exploitation': 'High',
    Location: 'Kenya',
    '2024': 28000000,
    Notes: 'National total biomass potential',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Biomass',
    'General Description': 'Agricultural residues',
    'Unit of Measure': 'tonnes/yr',
    'Status of Exploitation': 'Moderate',
    Location: 'Kenya',
    '2024': 4200000,
    Notes: 'National agricultural residue potential',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Hydro',
    'General Description': 'Hydroelectric potential',
    'Unit of Measure': 'MW',
    'Status of Exploitation': 'Low',
    Location: 'Kenya',
    '2024': 3000,
    Notes: 'National hydroelectric potential',
    Source: 'National Energy Report',
  },

  // INFRASTRUCTURE & ACCESS
  {
    Administration: 'NATIONAL',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kenya',
    '2024': 48,
    Notes: 'National average household connectivity',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Household count',
    'General Description': 'Number of Households',
    'Unit of Measure': 'Count',
    'Status of Exploitation': 'Active',
    Location: 'Kenya',
    '2019': 7200000,
    '2020': 7350000,
    '2021': 7505000,
    '2022': 7665000,
    '2023': 7830000,
    '2024': 8000000,
    '2025': 8175000,
    '2026': 8355000,
    '2027': 8540000,
    '2028': 8730000,
    '2029': 8925000,
    '2030': 9125000,
    '2031': 9330000,
    '2032': 9540000,
    '2033': 9755000,
    Notes: 'National total number of households',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of MSMEs (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kenya',
    '2024': 65,
    Notes: 'National average MSME connectivity',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Households connected to solar home systems (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kenya',
    '2024': 12,
    Notes: 'National solar home system adoption',
    Source: 'National Energy Report',
  },

  // ENERGY DEMAND & CONSUMPTION
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Households (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kenya',
    '2019': 2210000000,
    '2020': 2305000000,
    '2021': 2404000000,
    '2022': 2508000000,
    '2023': 2616000000,
    '2024': 2800000000,
    '2025': 2912000000,
    '2026': 3029000000,
    '2027': 3151000000,
    '2028': 3279000000,
    '2029': 3412000000,
    '2030': 3552000000,
    '2031': 3698000000,
    '2032': 3852000000,
    '2033': 4013000000,
    Notes: 'National total household electricity consumption',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Commercial and Industrial Customers (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kenya',
    '2019': 3850000000,
    '2020': 4008000000,
    '2021': 4172000000,
    '2022': 4344000000,
    '2023': 4525000000,
    '2024': 5200000000,
    '2025': 5408000000,
    '2026': 5623000000,
    '2027': 5847000000,
    '2028': 6080000000,
    '2029': 6323000000,
    '2030': 6576000000,
    '2031': 6839000000,
    '2032': 7113000000,
    '2033': 7398000000,
    Notes: 'National C&I electricity consumption',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Public Institutions / Facilities (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kenya',
    '2019': 285000000,
    '2020': 298000000,
    '2021': 312000000,
    '2022': 328000000,
    '2023': 346000000,
    '2024': 365000000,
    '2025': 385000000,
    '2026': 407000000,
    '2027': 431000000,
    '2028': 457000000,
    '2029': 485000000,
    '2030': 515000000,
    '2031': 547000000,
    '2032': 582000000,
    '2033': 620000000,
    Notes: 'National public institutions electricity consumption',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Street lighting (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kenya',
    '2019': 142000000,
    '2020': 148000000,
    '2021': 154000000,
    '2022': 161000000,
    '2023': 169000000,
    '2024': 177000000,
    '2025': 186000000,
    '2026': 196000000,
    '2027': 206000000,
    '2028': 217000000,
    '2029': 229000000,
    '2030': 242000000,
    '2031': 256000000,
    '2032': 271000000,
    '2033': 287000000,
    Notes: 'National street lighting electricity consumption',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Total units sold (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kenya',
    '2019': 3575000000,
    '2020': 3725000000,
    '2021': 3885000000,
    '2022': 4055000000,
    '2023': 4235000000,
    '2024': 5742000000,
    '2025': 5995000000,
    '2026': 6258000000,
    '2027': 6535000000,
    '2028': 6825000000,
    '2029': 7129000000,
    '2030': 7449000000,
    '2031': 7784000000,
    '2032': 8137000000,
    '2033': 8508000000,
    Notes: 'National total electricity units sold',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Firewood %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Declining',
    Location: 'Kenya',
    '2024': 28,
    Notes: 'National average firewood usage',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Charcoal %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Stable',
    Location: 'Kenya',
    '2024': 32,
    Notes: 'National average charcoal usage',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kenya',
    '2024': 22,
    Notes: 'National average LPG usage',
    Source: 'National Energy Report',
  },
  {
    Administration: 'NATIONAL',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Electricity %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kenya',
    '2024': 8,
    Notes: 'National average electricity for cooking',
    Source: 'National Energy Report',
  },

  // ============ KILIFI COUNTY ============
  // ENERGY RESOURCE POTENTIAL - County's Energy Resources
  {
    Administration: 'Kilifi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Kilifi County',
    '2019': 5.2,
    '2020': 5.2,
    '2021': 5.2,
    '2022': 5.2,
    '2023': 5.2,
    '2024': 5.2,
    '2025': 5.3,
    '2026': 5.3,
    '2027': 5.3,
    '2028': 5.3,
    '2029': 5.3,
    '2030': 5.4,
    Notes: 'Consistent high solar potential year-round',
    Source: 'Table 2.8',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Wind',
    'General Description': 'Wind potential by area',
    'Unit of Measure': 'm/s',
    'Status of Exploitation': 'Moderate',
    Location: 'Kilifi County',
    '2019': 6.2,
    '2020': 6.2,
    '2021': 6.2,
    '2022': 6.2,
    '2023': 6.3,
    '2024': 6.3,
    '2025': 6.5,
    '2026': 6.6,
    '2027': 6.7,
    '2028': 6.8,
    '2029': 6.9,
    '2030': 7.0,
    Notes: 'Coastal wind resources with seasonal variation',
    Source: 'Table 2.9',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Biomass',
    'General Description': 'Wood fuel',
    'Unit of Measure': 'tonnes/yr',
    'Status of Exploitation': 'High',
    Location: 'Kilifi County',
    '2019': 450000,
    '2020': 455000,
    '2021': 460000,
    '2022': 465000,
    '2023': 470000,
    '2024': 475000,
    '2025': 480000,
    '2026': 485000,
    '2027': 490000,
    '2028': 495000,
    '2029': 500000,
    '2030': 505000,
    Notes: 'Primary cooking fuel in rural areas',
    Source: 'Table 2.1',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Biomass',
    'General Description': 'Agricultural residues',
    'Unit of Measure': 'tonnes/yr',
    'Status of Exploitation': 'Moderate',
    Location: 'Kilifi County',
    '2019': 120000,
    '2020': 125000,
    '2021': 130000,
    '2022': 135000,
    '2023': 140000,
    '2024': 145000,
    '2025': 150000,
    '2026': 155000,
    '2027': 160000,
    '2028': 165000,
    '2029': 170000,
    '2030': 175000,
    Notes: 'Coconut husks, cashew shells, rice bran',
    Source: 'Table 2.2',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Hydro',
    'General Description': 'Potential for different sites',
    'Unit of Measure': 'MW',
    'Status of Exploitation': 'Low',
    Location: 'Kilifi County',
    '2019': 15,
    '2020': 15,
    '2021': 15,
    '2022': 15,
    '2023': 15,
    '2024': 15,
    '2025': 15,
    '2026': 15,
    '2027': 15,
    '2028': 15,
    '2029': 15,
    '2030': 15,
    Notes: 'Limited by rainfall seasonality',
    Source: 'Table 2.7',
  },

  // INFRASTRUCTURE & ACCESS - Electricity Connectivity Progression
  {
    Administration: 'Kilifi',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kilifi County',
    '2019': 25,
    '2020': 28,
    '2021': 31,
    '2022': 34,
    '2023': 37,
    '2024': 40,
    '2025': 43,
    '2026': 46,
    '2027': 49,
    '2028': 52,
    '2029': 55,
    '2030': 60,
    Notes: 'Target: 60% by 2030',
    Source: 'Table 3.1 (a)',
  },
  {
    Administration: 'Kilifi',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of MSMEs (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kilifi County',
    '2019': 45,
    '2020': 48,
    '2021': 51,
    '2022': 54,
    '2023': 57,
    '2024': 60,
    '2025': 65,
    '2026': 70,
    '2027': 75,
    '2028': 80,
    '2029': 85,
    '2030': 90,
    Notes: 'Higher priority for economic development',
    Source: 'Table 3.1 (a)',
  },
  {
    Administration: 'Kilifi',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Households connected to solar home systems (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kilifi County',
    '2019': 8,
    '2020': 10,
    '2021': 12,
    '2022': 14,
    '2023': 16,
    '2024': 18,
    '2025': 22,
    '2026': 26,
    '2027': 30,
    '2028': 35,
    '2029': 40,
    '2030': 45,
    Notes: 'Off-grid solar systems gaining adoption',
    Source: 'Table 3.1 (a)',
  },

  // ENERGY DEMAND & CONSUMPTION - Electricity Consumption Summary
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Households (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kilifi County',
    '2019': 85000000,
    '2020': 88000000,
    '2021': 92000000,
    '2022': 96000000,
    '2023': 100000000,
    '2024': 105000000,
    '2025': 110000000,
    '2026': 120000000,
    '2027': 130000000,
    '2028': 140000000,
    '2029': 150000000,
    '2030': 160000000,
    Notes: 'Growing with electrification',
    Source: 'Table 3.1 (b)',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Commercial and Industrial Customers (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kilifi County',
    '2019': 120000000,
    '2020': 135000000,
    '2021': 152000000,
    '2022': 170000000,
    '2023': 190000000,
    '2024': 210000000,
    '2025': 235000000,
    '2026': 265000000,
    '2027': 300000000,
    '2028': 340000000,
    '2029': 380000000,
    '2030': 420000000,
    Notes: 'Tourism and agricultural processing growth',
    Source: 'Table 3.1 (b)',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Firewood %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Declining',
    Location: 'Kilifi County',
    '2019': 45,
    '2020': 43,
    '2021': 41,
    '2022': 39,
    '2023': 37,
    '2024': 35,
    '2025': 32,
    '2026': 28,
    '2027': 25,
    '2028': 22,
    '2029': 20,
    '2030': 18,
    Notes: 'Transition to cleaner fuels',
    Source: 'Table 3.2 (a)',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Charcoal %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Stable',
    Location: 'Kilifi County',
    '2019': 35,
    '2020': 36,
    '2021': 37,
    '2022': 37,
    '2023': 36,
    '2024': 35,
    '2025': 33,
    '2026': 30,
    '2027': 27,
    '2028': 25,
    '2029': 23,
    '2030': 20,
    Notes: 'Primary cooking fuel, gradual replacement',
    Source: 'Table 3.2 (a)',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kilifi County',
    '2019': 12,
    '2020': 14,
    '2021': 16,
    '2022': 18,
    '2023': 20,
    '2024': 22,
    '2025': 25,
    '2026': 28,
    '2027': 31,
    '2028': 34,
    '2029': 37,
    '2030': 40,
    Notes: 'Increasing availability and affordability',
    Source: 'Table 3.2 (a)',
  },
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Electricity %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kilifi County',
    '2019': 5,
    '2020': 6,
    '2021': 7,
    '2022': 8,
    '2023': 9,
    '2024': 10,
    '2025': 12,
    '2026': 14,
    '2027': 16,
    '2028': 18,
    '2029': 20,
    '2030': 22,
    Notes: 'Electric cooking adoption with grid expansion',
    Source: 'Table 3.2 (a)',
  },

  // ============ KIAMBU COUNTY ============
  {
    Administration: 'Kiambu',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Kiambu County',
    '2019': 4.7,
    '2020': 4.7,
    '2021': 4.7,
    '2022': 4.7,
    '2023': 4.7,
    '2024': 4.8,
    '2025': 4.8,
    '2026': 4.9,
    '2027': 4.9,
    '2028': 5.0,
    '2029': 5.0,
    '2030': 5.0,
    Notes: 'Moderate solar potential, elevation dependent',
    Source: 'Table 2.8',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Wind',
    'General Description': 'Wind potential by area',
    'Unit of Measure': 'm/s',
    'Status of Exploitation': 'Low',
    Location: 'Kiambu County',
    '2019': 4.1,
    '2020': 4.1,
    '2021': 4.1,
    '2022': 4.1,
    '2023': 4.2,
    '2024': 4.2,
    '2025': 4.3,
    '2026': 4.3,
    '2027': 4.4,
    '2028': 4.4,
    '2029': 4.5,
    '2030': 4.5,
    Notes: 'Limited by geographic location and vegetation',
    Source: 'Table 2.9',
  },
  {
    Administration: 'Kiambu',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kiambu County',
    '2019': 65,
    '2020': 68,
    '2021': 71,
    '2022': 74,
    '2023': 76,
    '2024': 78,
    '2025': 80,
    '2026': 82,
    '2027': 84,
    '2028': 86,
    '2029': 88,
    '2030': 90,
    Notes: 'High electrification as urban/peri-urban county',
    Source: 'Table 3.1 (a)',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Demand & Consumption',
    Theme: 'Summary of Electricity Consumption in the County',
    Sector: 'Electricity consumption',
    'General Description': 'Households (kWh)',
    'Unit of Measure': 'kWh',
    'Status of Exploitation': 'Active',
    Location: 'Kiambu County',
    '2019': 250000000,
    '2020': 265000000,
    '2021': 280000000,
    '2022': 298000000,
    '2023': 318000000,
    '2024': 340000000,
    '2025': 365000000,
    '2026': 392000000,
    '2027': 420000000,
    '2028': 450000000,
    '2029': 480000000,
    '2030': 510000000,
    Notes: 'Higher consumption due to urban density',
    Source: 'Table 3.1 (b)',
  },

  // ============ KIAMBU COUNTY ============
  // ENERGY RESOURCE POTENTIAL
  {
    Administration: 'Kiambu',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Kiambu County',
    '2024': 4.8,
    '2030': 5.0,
    Notes: 'High altitude reduces solar potential',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Wind',
    'General Description': 'Wind potential by area',
    'Unit of Measure': 'm/s',
    'Status of Exploitation': 'Low',
    Location: 'Kiambu County',
    '2024': 4.2,
    '2030': 4.5,
    Notes: 'Limited wind resources inland',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Biomass',
    'General Description': 'Wood fuel',
    'Unit of Measure': 'tonnes/yr',
    'Status of Exploitation': 'High',
    Location: 'Kiambu County',
    '2024': 385000,
    '2030': 410000,
    Notes: 'Extensive forest resources',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kiambu County',
    '2024': 68,
    '2030': 85,
    Notes: 'Close to Nairobi - higher connectivity',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Households connected to solar home systems (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kiambu County',
    '2024': 12,
    '2030': 25,
    Notes: 'Growing off-grid solar adoption',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Firewood %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Decreasing',
    Location: 'Kiambu County',
    '2024': 42,
    '2030': 25,
    Notes: 'Declining as LPG adoption increases',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kiambu County',
    '2024': 35,
    '2030': 55,
    Notes: 'Rapid LPG adoption in urban/peri-urban areas',
    Source: 'County Energy Profile',
  },

  // ============ NYANDARUA COUNTY ============
  // ENERGY RESOURCE POTENTIAL
  {
    Administration: 'Nyandarua',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Nyandarua County',
    '2024': 4.5,
    '2030': 4.7,
    Notes: 'High altitude and cloudy conditions limit solar',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nyandarua',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Hydro',
    'General Description': 'Potential for different sites',
    'Unit of Measure': 'MW',
    'Status of Exploitation': 'Moderate',
    Location: 'Nyandarua County',
    '2024': 35,
    '2030': 35,
    Notes: 'Water towers provide hydro potential',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nyandarua',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Biomass',
    'General Description': 'Agricultural residues',
    'Unit of Measure': 'tonnes/yr',
    'Status of Exploitation': 'Moderate',
    Location: 'Nyandarua County',
    '2024': 95000,
    '2030': 110000,
    Notes: 'Potato and maize residues',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nyandarua',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Nyandarua County',
    '2024': 45,
    '2030': 70,
    Notes: 'Rural areas being progressively connected',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nyandarua',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of MSMEs (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Nyandarua County',
    '2024': 55,
    '2030': 80,
    Notes: 'Agricultural processing businesses',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nyandarua',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Charcoal %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'High',
    Location: 'Nyandarua County',
    '2024': 38,
    '2030': 20,
    Notes: 'Traditional fuel but target is reduction',
    Source: 'County Energy Profile',
  },

  // ============ MOMBASA COUNTY ============
  // ENERGY RESOURCE POTENTIAL
  {
    Administration: 'Mombasa',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Mombasa County',
    '2024': 5.3,
    '2030': 5.4,
    Notes: 'Excellent coastal solar potential',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Wind',
    'General Description': 'Wind potential by area',
    'Unit of Measure': 'm/s',
    'Status of Exploitation': 'High',
    Location: 'Mombasa County',
    '2024': 7.2,
    '2030': 7.5,
    Notes: 'Strong coastal and Indian Ocean winds',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Biomass',
    'General Description': 'Wood fuel',
    'Unit of Measure': 'tonnes/yr',
    'Status of Exploitation': 'Moderate',
    Location: 'Mombasa County',
    '2024': 125000,
    '2030': 120000,
    Notes: 'Limited due to urbanization',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Mombasa County',
    '2024': 75,
    '2030': 92,
    Notes: 'Urban county with good grid coverage',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of industries (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Mombasa County',
    '2024': 88,
    '2030': 98,
    Notes: 'Port city with industrial focus',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Mombasa County',
    '2024': 48,
    '2030': 70,
    Notes: 'Urban areas with high LPG penetration',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Electricity %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Mombasa County',
    '2024': 15,
    '2030': 25,
    Notes: 'Urban electric cooking adoption',
    Source: 'County Energy Profile',
  },

  // ============ NAIROBI COUNTY ============
  // ENERGY RESOURCE POTENTIAL
  {
    Administration: 'Nairobi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Nairobi County',
    '2024': 4.9,
    '2030': 5.1,
    Notes: 'High altitude reduces solar slightly',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nairobi',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Nairobi County',
    '2024': 82,
    '2030': 95,
    Notes: 'Capital city with highest connectivity',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nairobi',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of industries (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Nairobi County',
    '2024': 95,
    '2030': 99,
    Notes: 'Nearly complete industrial coverage',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nairobi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Nairobi County',
    '2024': 52,
    '2030': 72,
    Notes: 'Metropolitan area with high LPG usage',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nairobi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Electricity %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Nairobi County',
    '2024': 20,
  },
  // ============ COMPREHENSIVE HISTORICAL + PROJECTION DATA ============
  // Adding comprehensive data spanning 2019-2030 for all counties
  
  // KILIFI - Energy Resource Potential (Solar Potential)
  {
    Administration: 'Kilifi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Kilifi County',
    '2019': 4.6,
    '2020': 4.65,
    '2021': 4.7,
    '2022': 4.75,
    '2023': 4.8,
    '2024': 4.85,
    '2025': 4.88,
    '2026': 4.9,
    '2027': 4.92,
    '2028': 4.94,
    '2029': 4.97,
    '2030': 5.0,
    Notes: 'Coastal county with excellent solar potential',
    Source: 'County Energy Profile',
  },
  // KILIFI - Infrastructure (Electricity Connectivity)
  {
    Administration: 'Kilifi',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kilifi County',
    '2019': 35,
    '2020': 38,
    '2021': 41,
    '2022': 45,
    '2023': 50,
    '2024': 55,
    '2025': 62,
    '2026': 68,
    '2027': 74,
    '2028': 80,
    '2029': 87,
    '2030': 92,
    Notes: 'Steady progress in household electrification',
    Source: 'County Energy Profile',
  },
  // KILIFI - Cooking Fuels (Firewood)
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Firewood %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Decreasing',
    Location: 'Kilifi County',
    '2019': 72,
    '2020': 70,
    '2021': 68,
    '2022': 65,
    '2023': 62,
    '2024': 58.1,
    '2025': 52,
    '2026': 46,
    '2027': 38,
    '2028': 30,
    '2029': 22,
    '2030': 15,
    Notes: 'Declining firewood usage with cleaner fuel adoption',
    Source: 'County Energy Profile',
  },
  // KILIFI - Cooking Fuels (LPG)
  {
    Administration: 'Kilifi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kilifi County',
    '2019': 8,
    '2020': 10,
    '2021': 12,
    '2022': 15,
    '2023': 18,
    '2024': 21,
    '2025': 28,
    '2026': 35,
    '2027': 45,
    '2028': 55,
    '2029': 65,
    '2030': 72,
    Notes: 'Rapid adoption of LPG for cooking',
    Source: 'County Energy Profile',
  },

  // KIAMBU - Full data spanning 2019-2030
  {
    Administration: 'Kiambu',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Kiambu County',
    '2019': 4.5,
    '2020': 4.55,
    '2021': 4.6,
    '2022': 4.65,
    '2023': 4.7,
    '2024': 4.8,
    '2025': 4.85,
    '2026': 4.88,
    '2027': 4.9,
    '2028': 4.92,
    '2029': 4.96,
    '2030': 5.0,
    Notes: 'High altitude reduces solar potential',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Kiambu County',
    '2019': 58,
    '2020': 60,
    '2021': 62,
    '2022': 64,
    '2023': 66,
    '2024': 68,
    '2025': 72,
    '2026': 76,
    '2027': 80,
    '2028': 82,
    '2029': 84,
    '2030': 85,
    Notes: 'High electrification as urban/peri-urban county',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Firewood %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Decreasing',
    Location: 'Kiambu County',
    '2019': 58,
    '2020': 56,
    '2021': 54,
    '2022': 50,
    '2023': 46,
    '2024': 42,
    '2025': 36,
    '2026': 32,
    '2027': 28,
    '2028': 25,
    '2029': 25,
    '2030': 25,
    Notes: 'Declining as LPG adoption increases',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Kiambu',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Kiambu County',
    '2019': 22,
    '2020': 25,
    '2021': 28,
    '2022': 32,
    '2023': 34,
    '2024': 35,
    '2025': 42,
    '2026': 48,
    '2027': 55,
    '2028': 60,
    '2029': 63,
    '2030': 55,
    Notes: 'Rapid LPG adoption in urban/peri-urban areas',
    Source: 'County Energy Profile',
  },

  // NYANDARUA - Full data spanning 2019-2030
  {
    Administration: 'Nyandarua',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Nyandarua County',
    '2019': 4.2,
    '2020': 4.25,
    '2021': 4.3,
    '2022': 4.35,
    '2023': 4.4,
    '2024': 4.5,
    '2025': 4.55,
    '2026': 4.58,
    '2027': 4.6,
    '2028': 4.62,
    '2029': 4.65,
    '2030': 4.7,
    Notes: 'High altitude and cloudy conditions limit solar',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nyandarua',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Nyandarua County',
    '2019': 28,
    '2020': 31,
    '2021': 34,
    '2022': 37,
    '2023': 40,
    '2024': 45,
    '2025': 52,
    '2026': 58,
    '2027': 64,
    '2028': 67,
    '2029': 69,
    '2030': 70,
    Notes: 'Rural areas being progressively connected',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nyandarua',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'Charcoal %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'High',
    Location: 'Nyandarua County',
    '2019': 48,
    '2020': 46,
    '2021': 44,
    '2022': 42,
    '2023': 40,
    '2024': 38,
    '2025': 32,
    '2026': 28,
    '2027': 24,
    '2028': 20,
    '2029': 20,
    '2030': 20,
    Notes: 'Traditional fuel but target is reduction',
    Source: 'County Energy Profile',
  },

  // MOMBASA - Full data spanning 2019-2030
  {
    Administration: 'Mombasa',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Mombasa County',
    '2019': 5.0,
    '2020': 5.05,
    '2021': 5.1,
    '2022': 5.15,
    '2023': 5.2,
    '2024': 5.3,
    '2025': 5.32,
    '2026': 5.34,
    '2027': 5.36,
    '2028': 5.38,
    '2029': 5.39,
    '2030': 5.4,
    Notes: 'Excellent coastal solar potential',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Mombasa County',
    '2019': 68,
    '2020': 70,
    '2021': 71,
    '2022': 72,
    '2023': 73,
    '2024': 75,
    '2025': 80,
    '2026': 85,
    '2027': 88,
    '2028': 90,
    '2029': 91,
    '2030': 92,
    Notes: 'Urban county with good grid coverage',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Mombasa',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Mombasa County',
    '2019': 32,
    '2020': 35,
    '2021': 38,
    '2022': 41,
    '2023': 44,
    '2024': 48,
    '2025': 55,
    '2026': 60,
    '2027': 65,
    '2028': 68,
    '2029': 70,
    '2030': 70,
    Notes: 'Urban areas with high LPG penetration',
    Source: 'County Energy Profile',
  },

  // NAIROBI - Full data spanning 2019-2030
  {
    Administration: 'Nairobi',
    Category: 'Energy Resource Potential',
    Theme: "County's Energy Resources",
    Sector: 'Solar',
    'General Description': 'Solar radiation by area',
    'Unit of Measure': 'kWh/m²/day',
    'Status of Exploitation': 'Assessed',
    Location: 'Nairobi County',
    '2019': 4.7,
    '2020': 4.75,
    '2021': 4.8,
    '2022': 4.85,
    '2023': 4.88,
    '2024': 4.9,
    '2025': 4.95,
    '2026': 4.98,
    '2027': 5.0,
    '2028': 5.02,
    '2029': 5.05,
    '2030': 5.1,
    Notes: 'High altitude reduces solar slightly',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nairobi',
    Category: 'Infrastructure & Access',
    Theme: 'Electricity Connectivity Progression in the County',
    Sector: 'Electricity connection',
    'General Description': 'Total connectivity of households (%)',
    'Unit of Measure': '%',
    'Status of Exploitation': 'In Progress',
    Location: 'Nairobi County',
    '2019': 75,
    '2020': 77,
    '2021': 78,
    '2022': 79,
    '2023': 80,
    '2024': 82,
    '2025': 87,
    '2026': 90,
    '2027': 92,
    '2028': 93,
    '2029': 94,
    '2030': 95,
    Notes: 'Capital city with highest connectivity',
    Source: 'County Energy Profile',
  },
  {
    Administration: 'Nairobi',
    Category: 'Energy Demand & Consumption',
    Theme: 'Percentage of households by main sources of cooking fuels in the County',
    Sector: 'Fuel type',
    'General Description': 'LPG %',
    'Unit of Measure': '%',
    'Status of Exploitation': 'Growing',
    Location: 'Nairobi County',
    '2019': 38,
    '2020': 41,
    '2021': 44,
    '2022': 47,
    '2023': 50,
    '2024': 52,
    '2025': 58,
    '2026': 63,
    '2027': 68,
    '2028': 70,
    '2029': 71,
    '2030': 72,
    Notes: 'Metropolitan area with high LPG usage',
    Source: 'County Energy Profile',
  },
]

// Helper functions for data access
export function getUniqueThematicAreas(): string[] {
  const themes = new Set<string>()
  energyData.forEach((item) => {
    themes.add(item.Theme)
  })
  return Array.from(themes).sort()
}

export function getCountyData(county: string): EnergyDataPoint[] {
  return energyData.filter((item) => item.Administration === county)
}

export function getCountyCategories(county: string): string[] {
  const data = getCountyData(county)
  const categories = new Set<string>()
  data.forEach((item) => {
    categories.add(item.Category)
  })
  return Array.from(categories)
}

export function extractNumericValue(value: unknown): number | null {
  if (value === null || value === undefined) return null
  if (typeof value === 'number') return value
  if (typeof value === 'string') {
    const num = parseFloat(value.trim())
    return isNaN(num) ? null : num
  }
  return null
}

export function getUniqueCounties(): string[] {
  const counties = new Set<string>()
  energyData.forEach((item) => {
    counties.add(item.Administration)
  })
  return Array.from(counties).sort()
}

export function getDataByCounty(county: string): EnergyDataPoint[] {
  return energyData.filter((item) => item.Administration === county)
}

export function getDataByThematicArea(theme: string): EnergyDataPoint[] {
  return energyData.filter((item) => item.Theme === theme)
}

export function getDataByCountyAndThematic(county: string, theme: string): EnergyDataPoint[] {
  return energyData.filter((item) => item.Administration === county && item.Theme === theme)
}
